config/routes.rb
Rails.application.routes.draw do
  root to: 'photos#index'
  get 'photos', to: 'photos#index'

  get 'photos/random'
  get 'photos/favorites'
  get 'search', to: 'photos#search'

  scope path: 'photo/:photo_id' do
    post   'fav',   to: 'favorites#create',  as: 'photo_favorites'
    delete 'unfav', to: 'favorites#destroy', as: 'photo_favorite'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :photo_id, presence: true

  scope :recent, -> { order(created_at: :desc) }
end

app/models/photo.rb
class Photo
  include ActiveModel::Model

  attr_accessor :id, :description, :image_url, :thumb_url, :source_url, 
                :user_id, :user_name, :user_url

  validates :id, presence: true
  validates :image_url, presence: true

  def favorites
    Favorite.where("photo_id = ?", self.id)
  end

  def is_favorite?
    self.favorites.exists?
  end

  def self.get_photos
    Unsplash::API.get_photos
  end

  def self.get_random_photos
    Unsplash::API.get_random_photos
  end

  def self.get_search_photos(query)
    Unsplash::API.get_search_photos(query: query)
  end

  def self.get_favorites_photos
    Unsplash::API.get_favorites_photos
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @photo_id = params[:photo_id]
    @favorite = Favorite.find_by(photo_id: @photo_id)
    unless @favorite
      @favorite = Favorite.create(photo_id: @photo_id)
      render
    end
  end

  def destroy
    @photo_id = params[:photo_id]
    @favorite = Favorite.find_by(photo_id: @photo_id)
    if @favorite&.destroy
      render
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @title  = 'Photos'
    @header = 'Recently Photos'
    @photos = Photo.get_photos
  end

  def random
    @title  = 'Random'
    @header = 'Random Photos'
    @photos = Photo.get_random_photos
    render :index
  end

  def search
    @title  = 'Search'
    @header = "Related searches to '#{search_param[:query]}'"
    @photos = Photo.get_search_photos(search_param[:query])
    render :index
  end

  def favorites
    @title  = 'Favorites'
    @header = 'Favorite Photos'
    @photos = Photo.get_favorites_photos
    render :index
  end

  private
    def search_param
      params.permit(:query)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    if content_for?(:title)
      "IdeaGallery - #{content_for(:title)}"
    else
      "IdeaGallery"
    end
  end

  def nav_link_to(text, url)
    classes = ['nav-link']
    classes << 'active' if current_page?(url)
    link_to(text, url, class: classes.join(' '))
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def fav_classes(is_favorite)
    is_favorite ? "btn btn-info hidden" : "btn btn-info"
  end

  def unfav_classes(is_favorite)
    is_favorite ? "btn btn-secondary" : "btn btn-secondary hidden"
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/favorites/create.js.erb
var favorite_card_footer = document.querySelector('.card[data-id="<%= @photo_id %>"] .card-footer');
var fav_button   = favorite_card_footer.querySelector('#fav');
var unfav_button = favorite_card_footer.querySelector('#unfav');
var parent_node  = fav_button.parentNode;

fav_button.classList.add("hidden");
unfav_button.classList.remove("hidden");

app/views/favorites/destroy.js.erb
var favorite_card_footer = document.querySelector('.card[data-id="<%= @photo_id %>"] .card-footer');
var fav_button   = favorite_card_footer.querySelector('#fav');
var unfav_button = favorite_card_footer.querySelector('#unfav');
var parent_node  = unfav_button.parentNode;

unfav_button.classList.add("hidden");
fav_button.classList.remove("hidden");

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <a class="navbar-brand" href="<%= root_path %>">
    <img src="https://ideaware.co/wp-content/uploads/2018/02/Logosimbolo-Ideaware-azul-01-700x543.png" width="35" height="25" class="d-inline-block align-top" alt="">
    IdeaGallery
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= nav_link_to 'Photos', photos_path %>
      </li>
      <li class="nav-item">
        <%= nav_link_to 'Random', photos_random_path %>
      </li>
      <li class="nav-item">
        <%= nav_link_to 'Favorites', photos_favorites_path %>
      </li>
    </ul>
    <%= form_with url: search_path, method: :get, local: true, class: 'form-inline my-2 my-lg-0' do |form| %>
      <%= form.search_field :query, size: 30, placeholder: 'Search...', class: 'form-control mr-sm-2' %>
      <%= form.submit 'Search', class: 'btn btn-outline-info my-2 my-sm-0' %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/navbar" %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/photos/_not_found.html.erb
<div class="col text-center">
  <img src="<%= asset_path('no_found_photos.png') %>" alt="no photo founded" width="300" height="225">
</div>

app/views/photos/_photo_card.html.erb
<div class="col-8 offset-2 col-sm-6 offset-sm-0 col-lg-4 mb-4">
  <div class="card card-layout" data-id="<%= photo.id %>">
    <a href="<%= photo.source_url %>">
      <%= image_tag photo.thumb_url, class: 'card-img-top rounded', height: '200px' %>
    </a>
    <a href="<%= photo.user_url %>">
      <p class="mx-3 my-0 text-center"><small class="text-muted">By: <%= photo.user_name %></small></p>
    </a>
    <div class="card-body px-2 py-2">
      <p class="lead text-truncate mb-0"><%= photo.description %></p>
    </div>
    <div class="card-footer text-right px-2 py-2">
      <%= button_to 'Unmark', photo_favorite_path(photo.id), method: :delete, remote: true, data: { toggle: 'tooltip', placement: 'left' }, id: 'unfav', class: unfav_classes(photo.is_favorite?), title:"Unmark as a favorite" %>
      <%= button_to 'Mark', photo_favorites_path(photo.id), remote: true, data: { toggle: 'tooltip', placement: 'left' }, id: 'fav', class: fav_classes(photo.is_favorite?), title:"Mark as a favorite" %>
    </div>
  </div>
</div>

app/views/photos/index.html.erb
<% content_for(:title, @title) %>

<div class="row justify-content-sm-center">
  <div class="col-lg-10">
    <h2><%= @header %></h2>
    <hr>
    <div class="container">
      <div class="row">
        <% if @photos.any? %>
          <% @photos.each do |photo| %>
            <%= render partial: "photo_card", locals: { photo: photo } %>
          <% end %>
        <% else %>
          <%= render partial: "not_found" %>
        <% end %>
      </div>
    </div>

  </div>
</div>